require "config.options"
require "config.keybinds"
require "config.lazy"
require "config.colorscheme"
require "config.telescope"
require "config.treesitter"
require "config.neotree"
require "config.lsp"
